"""initial schema

Executes schema/wilkr.postgres.sql verbatim (as reviewed — corrected FK
directions, unquoted PostGIS geometry types, CHECK constraints and GIST
spatial indexes DBML can't express, DEFERRABLE stripped from all FKs)
rather than deriving DDL from the SQLAlchemy models, so nothing from that
review gets silently lost. See app/models/ for the matching ORM layer,
hand-synced against this schema.

Revision ID: 0001
Revises: 
Create Date: 2026-09-16
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

# Statements from schema/wilkr.postgres.sql, split so each op.execute()
# call carries exactly one statement — asyncpg prepares each execute()
# call individually and rejects multiple commands in one prepared
# statement, so the file can't be run as a single blob under the async
# engine.
_STATEMENTS = [
    'CREATE EXTENSION IF NOT EXISTS postgis;',
    'CREATE TABLE "users" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "username" varchar UNIQUE NOT NULL,\n  "email" varchar UNIQUE NOT NULL,\n  "display_name" varchar NOT NULL,\n  "weight_kg" float,\n  "height_cm" float,\n  "birth_date" date,\n  "resting_hr" int,\n  "max_hr" int,\n  "ftp_watts" int,\n  "timezone" varchar NOT NULL,\n  "created_at" timestamp NOT NULL DEFAULT (now()),\n  "updated_at" timestamp NOT NULL DEFAULT (now())\n);',
    'CREATE TABLE "user_preferences" (\n  "user_id" int PRIMARY KEY,\n  "unit_system" varchar NOT NULL DEFAULT \'metric\',\n  "default_sport_id" int,\n  "theme" varchar NOT NULL DEFAULT \'system\',\n  "extra" jsonb\n);',
    'CREATE TABLE "sports" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "name" varchar UNIQUE NOT NULL,\n  "category" varchar NOT NULL\n);',
    'CREATE TABLE "equipment" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "user_id" int NOT NULL,\n  "name" varchar NOT NULL,\n  "type" varchar NOT NULL,\n  "brand" varchar,\n  "model" varchar,\n  "purchased_at" date,\n  "retired_at" date\n);',
    'CREATE TABLE "equipment_sports" (\n  "equipment_id" int NOT NULL,\n  "sport_id" int NOT NULL,\n  PRIMARY KEY ("equipment_id", "sport_id")\n);',
    'CREATE TABLE "activities" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "user_id" int NOT NULL,\n  "sport_id" int NOT NULL,\n  "equipment_id" int,\n  "source" varchar NOT NULL,\n  "external_id" varchar NOT NULL,\n  "name" varchar NOT NULL,\n  "description" text,\n  "started_at" timestamp NOT NULL,\n  "moving_time_s" int NOT NULL,\n  "elapsed_time_s" int NOT NULL,\n  "distance_m" float NOT NULL,\n  "elevation_gain_m" float,\n  "avg_hr" int,\n  "max_hr" int,\n  "calories_kcal" int\n);',
    'CREATE TABLE "tracks" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "activity_id" int UNIQUE NOT NULL,\n  "geom" geometry(LineStringZ,4326) NOT NULL\n);',
    'CREATE TABLE "streams" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "activity_id" int NOT NULL,\n  "type" varchar NOT NULL,\n  "data" jsonb NOT NULL\n);',
    'CREATE TABLE "activity_laps" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "activity_id" int NOT NULL,\n  "lap_index" int NOT NULL,\n  "lap_type" varchar NOT NULL,\n  "started_at" timestamp NOT NULL,\n  "elapsed_time_s" int NOT NULL,\n  "distance_m" float,\n  "elevation_change_m" float,\n  "avg_speed_mps" float,\n  "max_speed_mps" float\n);',
    'CREATE TABLE "segments" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "name" varchar NOT NULL,\n  "sport_id" int NOT NULL,\n  "geom" geometry(LineString,4326) NOT NULL,\n  "created_at" timestamp NOT NULL DEFAULT (now())\n);',
    'CREATE TABLE "segment_efforts" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "segment_id" int NOT NULL,\n  "activity_id" int NOT NULL,\n  "elapsed_time_s" int NOT NULL,\n  "achieved_at" timestamp NOT NULL\n);',
    'CREATE TABLE "import_events" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "user_id" int NOT NULL,\n  "source" varchar NOT NULL,\n  "status" varchar NOT NULL,\n  "activity_id" int,\n  "error_message" text,\n  "created_at" timestamp NOT NULL DEFAULT (now())\n);',
    'CREATE TABLE "client_devices" (\n  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  "user_id" int NOT NULL,\n  "client_key" varchar UNIQUE NOT NULL,\n  "label" varchar,\n  "platform" varchar NOT NULL,\n  "app_version" varchar,\n  "first_seen_at" timestamp NOT NULL DEFAULT (now()),\n  "last_seen_at" timestamp NOT NULL DEFAULT (now())\n);',
    'CREATE UNIQUE INDEX "uq_activities_source_external_id" ON "activities" ("source", "external_id");',
    'COMMENT ON COLUMN "users"."weight_kg" IS \'for TSS, power-to-weight\';',
    'COMMENT ON COLUMN "users"."birth_date" IS \'for age-based HR zones\';',
    'COMMENT ON COLUMN "users"."ftp_watts" IS \'cycling, nullable\';',
    'COMMENT ON COLUMN "user_preferences"."user_id" IS \'shared PK/FK — one-to-one with users\';',
    'COMMENT ON COLUMN "user_preferences"."unit_system" IS \'metric or imperial, display only\';',
    'COMMENT ON COLUMN "user_preferences"."default_sport_id" IS \'nullable\';',
    'COMMENT ON COLUMN "user_preferences"."extra" IS \'future settings, no migration needed\';',
    'COMMENT ON COLUMN "sports"."name" IS \'running, road_cycling, mtb, alpine_ski, nordic_ski, hike, swim\';',
    'COMMENT ON COLUMN "sports"."category" IS \'endurance, strength, other\';',
    'COMMENT ON COLUMN "equipment"."name" IS \'e.g. Pegasus 40 (right)\';',
    'COMMENT ON COLUMN "equipment"."type" IS \'shoe, bike, ski, other\';',
    'COMMENT ON COLUMN "equipment"."retired_at" IS \'nullable — NULL means active; a date means retired. No separate is_active flag.\';',
    'COMMENT ON COLUMN "activities"."equipment_id" IS \'nullable\';',
    'COMMENT ON COLUMN "activities"."source" IS \'strava_import, garmin_sync, manual\';',
    'COMMENT ON COLUMN "activities"."external_id" IS \'dedupe key from source\';',
    'COMMENT ON COLUMN "activities"."description" IS \'nullable — merges Strava description + private note; nothing in wilkr is ever public, so that distinction does not matter here\';',
    'COMMENT ON COLUMN "activities"."max_hr" IS \'peak HR reached during this activity — distinct from users.max_hr, the training-zone ceiling\';',
    'COMMENT ON COLUMN "tracks"."geom" IS \'SRID 4326\';',
    'COMMENT ON COLUMN "streams"."type" IS \'heart_rate, elevation, speed, cadence, power\';',
    'COMMENT ON COLUMN "streams"."data" IS \'time-series array\';',
    'COMMENT ON COLUMN "activity_laps"."lap_type" IS \'run, lift, active, rest, interval\';',
    'COMMENT ON COLUMN "segments"."geom" IS \'SRID 4326\';',
    'COMMENT ON TABLE "segment_efforts" IS \'PR status is computed on read — RANK() OVER (PARTITION BY segment_id, activity.user_id ORDER BY elapsed_time_s) — not stored, so backfilled/out-of-order imports can never leave a stale is_pr flag.\';',
    'COMMENT ON COLUMN "import_events"."source" IS \'strava_import, garmin_sync, manual\';',
    'COMMENT ON COLUMN "import_events"."status" IS \'pending, success, failed, duplicate\';',
    'COMMENT ON COLUMN "import_events"."activity_id" IS \'nullable — set once the import succeeds\';',
    'COMMENT ON COLUMN "import_events"."error_message" IS \'nullable\';',
    'COMMENT ON TABLE "client_devices" IS \'Informational only, not an auth mechanism — Tailscale is the actual access-control layer. All devices share the one API key; this table just powers a "what has been using my library" dashboard, upserted on each check-in by client_key.\';',
    'COMMENT ON COLUMN "client_devices"."client_key" IS \'random ID generated once by the device and stored locally — not a credential, just a stable self-reported identity so repeat visits upsert the same row\';',
    'COMMENT ON COLUMN "client_devices"."label" IS \'friendly device name, e.g. "Ivan iPhone 15" — self-reported, editable later\';',
    'COMMENT ON COLUMN "client_devices"."platform" IS \'ios, web, other\';',
    'COMMENT ON COLUMN "client_devices"."app_version" IS \'nullable — self-reported client version\';',
    'ALTER TABLE "activities" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
    'ALTER TABLE "equipment" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
    'ALTER TABLE "user_preferences" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
    'ALTER TABLE "activities" ADD FOREIGN KEY ("sport_id") REFERENCES "sports" ("id");',
    'ALTER TABLE "segments" ADD FOREIGN KEY ("sport_id") REFERENCES "sports" ("id");',
    'ALTER TABLE "equipment_sports" ADD FOREIGN KEY ("sport_id") REFERENCES "sports" ("id");',
    'ALTER TABLE "equipment_sports" ADD FOREIGN KEY ("equipment_id") REFERENCES "equipment" ("id");',
    'ALTER TABLE "activities" ADD FOREIGN KEY ("equipment_id") REFERENCES "equipment" ("id");',
    'ALTER TABLE "tracks" ADD FOREIGN KEY ("activity_id") REFERENCES "activities" ("id");',
    'ALTER TABLE "streams" ADD FOREIGN KEY ("activity_id") REFERENCES "activities" ("id");',
    'ALTER TABLE "activity_laps" ADD FOREIGN KEY ("activity_id") REFERENCES "activities" ("id");',
    'ALTER TABLE "segment_efforts" ADD FOREIGN KEY ("activity_id") REFERENCES "activities" ("id");',
    'ALTER TABLE "segment_efforts" ADD FOREIGN KEY ("segment_id") REFERENCES "segments" ("id");',
    'ALTER TABLE "user_preferences" ADD FOREIGN KEY ("default_sport_id") REFERENCES "sports" ("id");',
    'ALTER TABLE "import_events" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
    'ALTER TABLE "import_events" ADD FOREIGN KEY ("activity_id") REFERENCES "activities" ("id");',
    'ALTER TABLE "client_devices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");',
    'ALTER TABLE "activities" ADD CONSTRAINT "ck_activities_source" CHECK ("source" IN (\'strava_import\', \'garmin_sync\', \'manual\'));',
    'ALTER TABLE "import_events" ADD CONSTRAINT "ck_import_events_source" CHECK ("source" IN (\'strava_import\', \'garmin_sync\', \'manual\'));',
    'ALTER TABLE "import_events" ADD CONSTRAINT "ck_import_events_status" CHECK ("status" IN (\'pending\', \'success\', \'failed\', \'duplicate\'));',
    'ALTER TABLE "streams" ADD CONSTRAINT "ck_streams_type" CHECK ("type" IN (\'heart_rate\', \'elevation\', \'speed\', \'cadence\', \'power\'));',
    'ALTER TABLE "activity_laps" ADD CONSTRAINT "ck_activity_laps_lap_type" CHECK ("lap_type" IN (\'run\', \'lift\', \'active\', \'rest\', \'interval\'));',
    'ALTER TABLE "equipment" ADD CONSTRAINT "ck_equipment_type" CHECK ("type" IN (\'shoe\', \'bike\', \'ski\', \'other\'));',
    'ALTER TABLE "sports" ADD CONSTRAINT "ck_sports_category" CHECK ("category" IN (\'endurance\', \'strength\', \'other\'));',
    'ALTER TABLE "user_preferences" ADD CONSTRAINT "ck_user_preferences_unit_system" CHECK ("unit_system" IN (\'metric\', \'imperial\'));',
    'ALTER TABLE "client_devices" ADD CONSTRAINT "ck_client_devices_platform" CHECK ("platform" IN (\'ios\', \'web\', \'other\'));',
    'CREATE INDEX "idx_tracks_geom" ON "tracks" USING GIST ("geom");',
    'CREATE INDEX "idx_segments_geom" ON "segments" USING GIST ("geom");',
]


def upgrade() -> None:
    for statement in _STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    op.execute('DROP SCHEMA public CASCADE; CREATE SCHEMA public;')

